version: '3.3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DJANGO_DATABASE_NAME}
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      POSTGRES_USER: ${DJANGO_DATABASE_USER}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - healthy_herbs


  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - healthy_herbs


volumes:

  postgres_data:

networks:
  healthy_herbs:
    driver: bridge